mode: "infer"
MI : True

# shared setting
factor: ""
model: ""
exp: "bn_lr7e-3"
gpu: 0 
backbone: "resnet50"
dataset: "CIFAR-100"
model_type: "pretrained"
model_number: 1
workers: 4
resume: null
infer: True
n_layer: 12
n_skip_l: 3
embedding_size: 256 
batch_size: 50
epochs: 50
crop_size: 513
groups: null
base_lr: 0.007
last_mult: 1.0
freeze_bn: False
weight_std: False
beta: False

# params for infer
infer_params:
  process_type: ""
  model_name: ""
  model_filename: ""


