mode: "infer"

# shared setting
factor: ""
model: "" # PIGNet_GSPonly ASPP Mask2Former
exp: "bn_lr7e-3"
backbone: "resnet50"
dataset: "cityscape"
model_type: "scratch"
model_number: 3
gpu: 0
workers: 4
resume: null
infer: True
n_layer: 12
n_skip_l: 3
embedding_size: 21
batch_size: 16
epochs: 50
crop_size: 513
groups: null
base_lr: 0.007
last_mult: 1.0
freeze_bn: False
weight_std: False
beta: False

# params for infer
infer_params:
  process_type: ""
  model_name: ""
  model_filename: ""


